### ISSUE TITLE
UIEventLogging conflicting with Twitter fabric sdk

### ISSUE THREAD

**Issue by indiandragon** [bugfender/BugfenderSDK-android-sample#1]
Hi Bugfender team,

```
Bugfender.enableUIEventLogging(MyApplication.this);
```

is conflicting with Twitter fabric sdk and there by causes twitter login to fail. When the UIEventLogging is disabled, the both logcat logging and twitter routines function as expected.

Logcat trace :

`Authorization completed with an error
                                                                  com.twitter.sdk.android.core.TwitterAuthException: Authorize failed.
                                                                      at com.twitter.sdk.android.core.identity.TwitterAuthClient.handleAuthorize(TwitterAuthClient.java:110)
                                                                      at com.twitter.sdk.android.core.identity.TwitterAuthClient.authorize(TwitterAuthClient.java:101)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:161)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                    at com.twitter.sdk
06-25 15:44:53.092 13770-13770/in.timebender.larynxbot E/Twitter: Authorization completed with an error
                                                                  com.twitter.sdk.android.core.TwitterAuthException: Authorize failed.
                                                                      at com.twitter.sdk.android.core.identity.TwitterAuthClient.handleAuthorize(TwitterAuthClient.java:110)
                                                                      at com.twitter.sdk.android.core.identity.TwitterAuthClient.authorize(TwitterAuthClient.java:101)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:161)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                      at com.twitter.sdk.android.core.identity.TwitterLoginButton$LoginClickListener.onClick(TwitterLoginButton.java:164)
                                                                      at com.bugfender.sdk.internal.a.c.d.onClick(Unknown Source)
                                                                    at com.twitter.sdk`

**Comment by jgimenez** [comment]
Hi @indiandragon . We're looking into it and as discussed over email we'll publish an update probably tomorrow. Thanks for reporting!

**Comment by jgimenez** [comment]
Version `0.4.1` has been released and should fix this. I'm closing the issue but please feel free to reopen if you find any problems.
