### ISSUE TITLE
it doesn't work...

### ISSUE THREAD

**Issue by LSDsl** [bugfender/BugfenderSDK-android-sample#11]
I see only bugdender sdk errors... many errors.. like this..

```
2018-06-02 14:53:44 +0300 System.err logcat  com.bugfender.sdk.a.a.b.b.c: com.bugfender.sdk.a.a.g.b.a.a: IO Exception: Error status: 500 / Response Message: Internal Server Error / Error Body: {"code":-1100,"message":"kafka server: Message was too large, server rejected it to avoid allocation error.","field":""}
2018-06-02 14:53:44 +0300 System.err logcat    at com.bugfender.sdk.a.a.b.a.b.a(Unknown Source)
2018-06-02 14:53:44 +0300 System.err logcat    at com.bugfender.sdk.a.a.g.a.a(Unknown Source)
2018-06-02 14:53:44 +0300 System.err logcat    at com.bugfender.sdk.a.a.b.a.b.a(Unknown Source)
2018-06-02 14:53:44 +0300 System.err logcat    ... 7 more
2018-06-02 14:53:44 +0300 System.err logcat    at com.bugfender.sdk.a.a.j.a.d.d.a(Unknown Source)```

**Comment by jgimenez** [comment]
As the message says, this is a server error, not SDK, so I'm closing this. If you have an issue not related to the SDK please contact us for support.

**Comment by LSDsl** [comment]
For me not differences -SDK not work. So it's bug.
