### ISSUE TITLE
App crash after upgrade from 0.6.4 to 0.7.3

### ISSUE THREAD

**Issue by billylo1** [bugfender/BugfenderSDK-android-sample#3]
Can you please take a look?  thx.

`                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
                                                                            at com.bugfender.sdk.a.a.b.o(Unknown Source)
                                                                            at com.bugfender.sdk.a.a.b.a(Unknown Source)
                                                                            at com.bugfender.sdk.a.a.b.a(Unknown Source)
                                                                            at com.bugfender.sdk.Bugfender.d(Unknown Source)
                                                                            at com.katlalabs.sidekick.SidekickApplication.onConnected(SidekickApplication.java:179)`

**Comment by jgimenez** [comment]
Hi Billy, thanks for the report. We heard about this issue yesterday and are working on a fix. We plan to release an update early next week, probably Tuesday, when we have completed the testing of the release candidate.

**Comment by jgimenez** [comment]
Hi @billylo1 , our Android SDK 0.7.4, just released, should be fixing this. Yours, Jordi.

**Comment by billylo1** [comment]
thx for the quick response, Jordi.
