### ISSUE TITLE
OOM with Bugfender SDK

### ISSUE THREAD

**Issue by bikranttripathi** [bugfender/BugfenderSDK-android-sample#5]
SDK Version: 1.0

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 18 byte allocation with 3888 free bytes and 3KB until OOM
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:580)
       at com.bugfender.sdk.a.a.b.r(Unknown Source)
       at com.bugfender.sdk.a.a.b.b(Unknown Source)
       at com.bugfender.sdk.a.a.b.a(Unknown Source)
       at com.bugfender.sdk.a.a.b.b(Unknown Source)
       at com.bugfender.sdk.a.a.d.c.a(Unknown Source)
       at com.bugfender.sdk.a.a.d.c.a(Unknown Source)
       at com.bugfender.sdk.a.a.d.c$1.a(Unknown Source)
       at com.bugfender.sdk.a.a.d.a.a(Unknown Source)
       at com.bugfender.sdk.a.a.d.a.c(Unknown Source)
       at com.bugfender.sdk.a.a.d.a.run(Unknown Source)
```

**Comment by jgimenez** [comment]
HI @bikranttripathi , we just released version `1.0.1`, it would be good if you can test with that version instead. An OOM is an application-wide issue. If your application uses too much memory, it will crash anywhere, including maybe in Bugfender stack. Did you isolate this issue to Bugfender? If so, could you please provide an example?

**Comment by bikranttripathi** [comment]
Hi @jgimenez, the thing is we didn't see this issue until we added Bugfender. I will check it again with the latest version to see if this is still an issue and will also verify it without the SDK as well :smiley:

**Comment by jgimenez** [comment]
OK, great!
